install.packages("data.table",repos= "http://lib.stat.cmu.edu/R/CRAN/")
install.packages("optparse",repos= "http://lib.stat.cmu.edu/R/CRAN/")
install.packages("Rtsne")
install.packages("caret")
install.packages("ClusterR")
install.packages("ggplot2")